### ISSUE TITLE
Google Analytics disappeared from Registry

### ISSUE THREAD

**Issue by hayfield** [ViderumGlobal/ckanext-iati#110] opened 2017-01-04 16:14 UTC
Google Analytics tracking on the Registry stopped working on 12th October 2016 (looking now, it's not included in the live source at all). This corresponds with the date of the [upgrade](http://www.aidtransparency.net/news/important-changes-to-the-iati-registry-api) from CKAN 2.1.4 to 2.5.2.

Looking at how [GA is included](https://github.com/ViderumGlobal/ckanext-iati/blob/master/ckanext/iati/theme/templates/base.html), it seems that a config file may have been overwritten during the upgrade. Of course, something else may be the cause.

Can GA tracking be restored to the Registry?
Additionally, if it is a config error, can a check undertaken to ensure no other settings were inadvertently disappeared during the version upgrade?

**Comment by dalepotter** [comment] 2017-01-10 12:05
@chrisviderum any thoughts on this one?

**Comment by chrisviderum** [comment] 2017-01-10 12:30
@dalepotter is there a way for you to confirm this?

We would need to log into your account to see, if the Google Analytics tracking is working correctly.

In the meantime, we can check, if config file was changed during the upgrade on the 12th October. Thank you very much for the hint @hayfield !

Best,

Chris

**Comment by dalepotter** [comment] 2017-01-10 13:56
Thanks for looking into this one - here's a screenshot from our analytics account which shows a large tail off in visitors in October - i.e. around the time of the upgrade to CKAN v2.5.2

![image](https://cloud.githubusercontent.com/assets/8247168/21808713/62ef6b78-d73c-11e6-9acf-f5fc576fb540.png)

More specifically, the analytics for the past month are showing 2 users and 21 sessions, which surely can;t be right?!

**Comment by pmartignoli** [comment] 2017-01-12 14:41
Hi @dalepotter ,
We would like to ensure this is now functioning however would require your login credentials for GA. A config file key had been overwritten which is now fixed. Would you please be able to confirm that GA is again functioning correctly? 
Thanks,

Paul

**Comment by hayfield** [comment] 2017-01-16 09:10
GA is now working on iatiregistry.org, yep.

**Comment by dalepotter** [comment] 2017-09-26 14:44
Sadly this issue has cropped up again, and since early July.

![image](https://user-images.githubusercontent.com/8247168/30866345-e19fef8c-a2d0-11e7-8d5c-3f47e08fe54a.png)

There is no sign of any google analytics tracking code in the Registry HTML. 

How has this occurred?  It's quite frustrating that this has cropped up again, as we have now lost all tracking information for these months. An international organisation has asked us for figures on their pages, and we are now unable to provide any information for them.

**Comment by newkdukem** [comment] 2017-09-29 12:40
A fix was deployed on the portal. The google analytics tracking code now is displayed near the bottom of the page.  @dalepotter can you confirm that now there is information for activities on the GA dashboard?

**Comment by dalepotter** [comment] 2017-10-06 14:01
The analytics for the site are now visible in Google analytics, so I will close this issue.

Thanks for fixing @newkdukem

**Comment by dalepotter** [comment] 2017-10-06 14:10
Also, forgot to mention - did we find out anything more about what caused this issue?

**Comment by JGulic** [comment] 2017-10-19 08:13
@dalepotter this issue was caused by an variable inccorectly set in configuration file. Setting the variable to correct value in the configuration file fixed this issue

**Comment by JGulic** [comment] 2017-10-30 09:45
@dalepotter I think we should close this issue, since it has already been resolved

**Comment by dalepotter** [comment] 2017-11-10 10:44
I'm now closing this issue as analytics are correctly showing for the past month. Thanks @newkdukem and @JGulic.

**Closed by dalepotter** 2017-11-10 10:44 UTC
Labels: bug, High priority
