### ISSUE TITLE
Datasets can show multiple resources

### ISSUE THREAD

**Issue by dalepotter** [ViderumGlobal/ckanext-iati#119] opened 2017-05-19 12:05 UTC
It seems that some datasets allow for multiple resource (i.e. data file) URLs to be added.  For example, with the [MERCY CORPS EUROPE Activity File-ET dataset](https://www.iatiregistry.org/dataset/mce-et):

![image](https://cloud.githubusercontent.com/assets/8247168/26246891/4af5ffb6-3c93-11e7-8854-8dc3ce83c716.png)

The following datasets are also affected by this issue:
- https://www.iatiregistry.org/dataset/mce-lb
- https://www.iatiregistry.org/dataset/open_university-sl

It doesn't seem possible to add more than one data file using the user interface, so I'm guessing that this occurs through the API?  Is there any validation to check that more than one data file cannot be added?

@pmartignoli - we have spoken about this previously and could I ask you and your developers to continue to investigate and publish updates to this issue.

**Comment by JGulic** [comment] 2017-05-19 12:51
Hi @dalepotter ,
yes, it isn’t possible to add more than one data file using the user interface, as validation prevents this; also, if the call is made from the API. We tested this and also tested out a patch and the validation doesn't allow adding more than one file. Since API calls use the functions that have this validation.

If you open the resources for the dataset, you'll notice that they are all the same.
I was investigating the publishers that have this issue and in some cases the publisher managed to add more than one resource to the dataset and in other cases the archiver manages to do this.

In the database, there are two options for the state of a resource: active (latest one) and deleted (older versions of the resource). The database entries show that there are multiple resources for a dataset where state is set to Active, not to Deleted, and archiver failed to update the dataset with newer information. Resources that have state set to Active are displayed in the portal and that's the reason that we have multiple resources displayed for one dataset.

I've added a check in the code for the state field of resource to keep the latest resource with state active, and set the other's to deleted. Since we couldn't reproduce this issue, it's better to add additional checks in the code that does this, so this issue doesn't happen again. Currently we are testing the solution and will send an update shortly.

**Comment by dalepotter** [comment] 2017-06-02 09:45
Thanks for this detail @JGulic - I'll await to hear a further update.

I'm presuming that the changes that you suggested in your last paragraph will mean that only the latest dataset is displayed, therefore resolving this issue?

**Comment by amy-silcock** [comment] 2017-07-14 15:22
This issue is still occurring for the following two publishers:
- https://www.iatiregistry.org/publisher/fco
- https://www.iatiregistry.org/publisher/mce

I have not checked to see whether it is affecting any other publishers.

New error messages have also appeared on other FCO files

**Comment by kmbn** [comment] 2017-07-31 12:39
@amy-silcock Regarding the publisher `fco`, action is required on the part of the publisher, or perhaps of IATI itself. The `Xml error` messages that are displayed for some of the datasets are occurring because the Data File URLs do not point to XML files anymore. The extra resources that some of the other `fco` datasets display also seem to be related to this issue. 

It seems like the gov.uk has changed the way it provides data for these datasets. For instance, the Data File URL for several of the `fco` datasets displaying `Xml error` messages (like `https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/570874/1479380876.84.xml` for dataset `fco-intsubs201516`) redirects to `https://www.gov.uk/government/publications/official-development-assistance-oda-international-subscriptions`. That page does provide a link to an XML file that we could use, but it's for all International Subscriptions from 2011 through 2017 rather than the yearly, quarterly, etc. timeframes of the datasets.

If there's only one source of data, it might make sense to create a single dataset for that file and just redirect the other datasets for the smaller timeframes to that master dataset.

**Comment by kmbn** [comment] 2017-07-31 12:50
There was one dataset for the publisher `mce` that had multiple resources. The dataset itself had an invalid name (`mcs-iq` rather than `mce-iq`, as per the rules for dataset names) that seems to have existed before that field was validated. As a result, attempts to automatically update thata dataset were failing. After correcting the dataset name, updating the dataset was successful and it only has one IATI XML resource now.

**Comment by newkdukem** [comment] 2017-08-07 23:17
This issue is still under investigation. We will update if any new information are discovered.

**Comment by newkdukem** [comment] 2017-09-15 11:19
The cause of this was that old datasets that were not purged and were wrongfully marked as active. The multiple resource validation is working properly. 
The multiple resource datasets were dealt with since and will no longer happen in the future.

**Closed** 2017-09-15 11:20 UTC
Labels: Medium priority
