### ISSUE TITLE
No duplicate IATI org IDs

### ISSUE THREAD

**Issue by amy-silcock** [ViderumGlobal/ckanext-iati#128] opened 2017-07-03 11:31 UTC
When creating a new publisher account on the IATI Registry please can we make it so that no duplicate IATI Organisation Identifiers are allowed? This would mean accounts cannot be created that share an IATI org ID with another IATI Registry pending or active account.

This feature currently exists for Publisher IDs. It would also be good to include similar wording explaining that the IATI org ID needs to be unique.

![image](https://user-images.githubusercontent.com/27764077/27791107-5b260ee6-5feb-11e7-84e0-5bd77045e852.png)

Thank you.

**Comment by amy-silcock** [comment] 2017-07-05 09:55
Hi Viderum,

Thank you for starting work on this.

One tweak needs to be made. I am trying to change a publisher account's status from 'pending' to 'active'. This is now showing: 
![image](https://user-images.githubusercontent.com/27764077/27859297-2a1d95ea-6170-11e7-8738-f7595d5b7084.png)
 
As I understand there is only one account with this identifier. And it is this account that now needs to be made active.

Thank you, Amy

**Comment by amy-silcock** [comment] 2017-07-10 13:28
Thanks for working on this. The above error is still occurring for other publisher accounts. For example I can't update the Global Alliance for TB Drug Development profile with their first published date because of the above error message.

For publisher accounts that are already active, or those whose status is going from pending to active need to be allowed to be updated.

New accounts which contain a non-unique ID should not be allowed to be created. This is when the message needs to occur.

Best wishes, Amy

**Comment by amy-silcock** [comment] 2017-07-24 13:25
Hi,

Today we've had a publisher set up an account with a duplicate Organisation ID to a previous account. There are reasons as to why they have done so, but this should now not be allowed by the registry.

![image](https://user-images.githubusercontent.com/27764077/28525356-d87f5b68-707b-11e7-8f7e-b93d0a1d7996.png)

**Comment by pmartignoli** [comment] 2017-07-25 09:23
@amy-silcock 

Creating a publisher with the same IATI ID as another publisher is blocked, editing an existing publisher to have the same ID as another publisher is blocked, but just editing a publisher that has an IATI ID (like changing it's state as in Amy's example) is permitted.

Publishers that currently have empty IATI ID fields can still be edited--you just have to give them an IATI ID. Publishers that currently have duplicate IATI IDs can also be edited--you just have to give one of them a new, unique IATI ID. Publishers (new or existing) cannot be created or updated with an empty IATI ID field because that field is required.

**Comment by amy-silcock** [comment] 2017-07-26 08:13
@pmartignoli 

In the case above a new publisher account was set up. You can currently access both publisher accounts.

Publisher ID:
- unesco-ihe
- ihedelft

**Comment by kmbn** [comment] 2017-07-26 08:34
@amy-silcock Perhaps there's been a misunderstanding. @pmartignoli meant that the validation he described is now in effect as of yesterday.

The new publisher account you're referring to was created before the updated validation came into effect. So you can access both of those accounts, and you can also access two other accounts that share a Publisher ID (`humana_houben` and `simone_sympany`, which were created in 2015).

From now on, publishers won't be able to use a Publisher ID (when creating a new publisher or editing an existing publisher to change/correct their Publisher ID) if it's already been registered by another publisher. And it's possible to edit a publisher, e.g., change their status, if they already have a Publisher ID, which address the issue you raised above (https://github.com/ViderumGlobal/ckanext-iati/issues/128#issuecomment-314105060). 'unesco-ihe' & `ihedelft` and `humana_houben` & `simone_sympany` are special cases here. You or the publisher's themselves will have to decide which one gets which Publisher ID, or if one is just a duplicate of the other and can be deleted, etc. The system will let you change their IDs or delete them as necessary.

There are also about 20 publishers with no Publisher ID at all--they predate the time that Publisher ID was made a required field. I can send you a list if you want to add the IDs or have the publisher add the IDs themselves. The fact that they don't have Publisher IDs doesn't affect their accessibility, so there's no rush to act there. However, if those publishers ever need to be updated (change of status, etc.), a Publisher ID will have to be added as well, since that field is required now.

**Comment by amy-silcock** [comment] 2017-07-26 09:44
@kmbn  @pmartignoli 

Just to clarify

1) We are talking about IATI Organisational ID's not Publisher ID's here
2) The previous issues have been resolved, the only outstanding one is to do with organisations ihedelft & unesco-ihe
3) The current issue is a new publisher account (ihedelft) was set up yesterday containing the same IATI org ID as another publisher account which is already publishing:
![image](https://user-images.githubusercontent.com/27764077/28612720-0d3159d4-71e8-11e7-8543-24e75d228ba2.png) 
It's Publisher ID is different, but the IATI org ID is not. This should not have been allowed.

The IATI teach team is in contact with the organisation, who happen to be the same but need to set up another account. We are managing this. The issue is that the Registry should not have not allowed this to happen.

**Comment by kmbn** [comment] 2017-07-26 09:51
Sorry, I didn't keep my nomenclature straight when writing my previous comment. We're both talking about, in this case, Identifier NL-KVK-41146484, correct? If so, just reread my previous comment with and replace all my mentions of Publisher ID with IATI org ID. (I'm sorry for the misunderstanding.) IHE Delft registered while the IATI org ID validation was turned off to deal with the fact the you couldn't update organizations (https://github.com/ViderumGlobal/ckanext-iati/issues/128#issuecomment-314105060). The modified validation is now in effect, meaning that 1) the IHE Delft situation cannot reoccur and 2) you can still edit organizations that do have IATI org IDs.

**Comment by amy-silcock** [comment] 2017-07-26 15:52
Good to know that this should be fixed @kmbn 

I'm guessing it took longer than expected to turn the validation back on once the previous error occurred?

**Comment by kmbn** [comment] 2017-07-28 13:36
`unesco-ihe` now redirects to `ihedelft`. In the future it would be a good idea to move the publisher and dataset redirects to the config file or possibly to an interface that sysadmins can update on their own.

**Comment by newkdukem** [comment] 2017-09-18 09:49
The duplicate IATI org IDs validation has been developed and deployed on production. 
Regarding the last comment from @kmbn, about publisher and dataset redirects, a new issue has been created https://github.com/ViderumGlobal/ckanext-iati/issues/135

**Closed by newkdukem** 2017-09-18 09:49 UTC
Labels: Medium priority

**Comment by amy-silcock** [comment] 2018-02-16 12:54
Two new publisher account have been created with the same IATI Org ID:

https://www.iatiregistry.org/publisher/111111_publisher
and
https://www.iatiregistry.org/publisher/111111

This should not be possible.

**Comment by kmbn** [comment] 2018-02-16 17:30
The publishers do not have the same IATI Org ID, though it does look like they do.

Publisher 111111_publisher has IATI Org ID `"BE-BCE_KBO-0421210424"` and publisher 111111 has IATI Org ID `"BE-BCE_KBO-0421210424 "` (the quotation marks are only included to make the space at the end of 111111's Org ID visible).

The IATI Org ID field has a validator that enforces uniqueness, but it does not have a validator that enforces formatting like trailing spaces, etc.

**Comment by andylolz** [comment] 2018-02-19 11:20
I’ve [asked a question over here](https://github.com/OpenDataServices/org-ids/issues/195), to get some clarity on what sort of additional validation should be applied here.
