### ISSUE TITLE
IATI Registry - Publisher List

### ISSUE THREAD

**Issue by amy-silcock** [ViderumGlobal/ckanext-iati#141] opened 2017-10-04 11:27 UTC
Hi Viderum,

We've noticed an error with the Registry Publisher page. If you use the URL https://www.iatiregistry.org/publisher then the ability to sort the columns disappears. The list of publishers is also no longer in alphabetical order, with the names starting in lower case being at the bottom of the list.

These errors are not present when using the URL without the www: https://iatiregistry.org/publisher

Please can this be sorted.

**Comment by minnaholi** [comment] 2017-10-05 12:18
@amy-silcock 

The fix has been applied. Please check that everything looks fine now.

**Comment by amy-silcock** [comment] 2017-10-05 12:19
@minnaholi 

Thanks Minna. It looks fine now.

**Comment by andylolz** [comment] 2017-10-06 07:53
It’s not at all clear what happened here! I don’t see any related commits to this repo… Did you restart something?

[Fwiw I wasn’t able to reproduce the bug when I checked on 2017-10-04.]

Sorry to weigh in on this… But it’s always so great when past issues are able to provide a useful reference, to understand what when wrong and how the problem was resolved. Otherwise you end up in this situation:

![wisdom_of_the_ancients](https://user-images.githubusercontent.com/464193/31268354-20182948-aa7c-11e7-8ec4-7b86ecb3d25f.png)

[source](https://xkcd.com/979/)

**Comment by dalepotter** [comment] 2017-10-06 14:22
Thanks for posting this @andylolz - I raised this point when we spoke with @minnaholi yesterday, so would be good to add the extra context.

N.B. We also spoke about the need for code change commits that are related to issues to be tagged to those issues, in line with the [contributing guide for the repository](https://github.com/ViderumGlobal/ckanext-iati/blob/master/CONTRIBUTING.rst).

**Comment by JGulic** [comment] 2017-10-18 13:25
@dalepotter this issue is not connected with this repository, so there isn't a commit that we can point to in order to make things more clear.
This issue appeared because CKAN by default supports setting up only one site_url variable in the configuration file, on which it relies for many features (especially in the front-end), also many CKAN features that need an absolute URL are using the site_url variable from the configuration file.
So in order for the features to work on a www version of the url, we've made changes in CKAN's configuration file for the portal, and added the 'www' version of the url to the [CORS policy whitelist](http://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-cors-origin-whitelist)(list of allowable origins). If needed, the CORS policy whitelist can be extended in the future.

**Comment by JGulic** [comment] 2017-10-25 14:05
@dalepotter I am closing this issue

**Closed by JGulic** 2017-10-25 14:05 UTC
Labels: High priority
