### ISSUE TITLE
Registry Slow To Respond Via Chrome

### ISSUE THREAD

**Issue by wendyrogers** [ViderumGlobal/ckanext-iati#82] opened 2016-08-23 10:36 UTC
Also raised via IATI Zendesk ticket 3941.

The  IATI Registry is currently taking a very long time to view/change pages etc. and has on a few occasions also timed out? I ususally use Chrome as my browser so I don't know if this a browser specific issue as it does appear to be slightly faster on Firefox?

@peppe1337 to investigate? TIA

**Comment by peppe1337** [comment] 2016-08-23 10:50
Hey @wendyrogers,

thanks for posting with. We will take a look at this.

Unfortunately I haven't received a Zendesk ticket about this. Or was the ticket raised at your system?

Can you maybe raise this to our ZenDesk account?

Thanks!

**Comment by wendyrogers** [comment] 2016-08-23 10:58
Many thanks @peppe1337 and just to let you know that I sent the request from our Help Desk to Yours and also CC'd you in as well?

**Comment by peppe1337** [comment] 2016-08-23 11:11
@wendyrogers received it!

**Comment by dalepotter** [comment] 2016-08-30 15:38
Just to add a more technical perspective, I can confirm that the registry seems to be performing relatively slowly - at least compared to all other sites I have tested.

Below tests done one after the other using a [curl command](https://viewsby.wordpress.com/2013/01/07/get-response-time-with-curl/) (results in seconds):

```
$ curl -o /dev/null -s -w %{time_total}\\n  http://www.google.com
0.071
$ curl -o /dev/null -s -w %{time_total}\\n  https://iatiregistry.org/
1.431
$ curl -o /dev/null -s -w %{time_total}\\n  https://iatiregistry.org/publisher
1.222
$ curl -o /dev/null -s -w %{time_total}\\n  http://www.bbc.co.uk/news
0.627
$ curl -o /dev/null -s -w %{time_total}\\n  http://iatistandard.org/
0.084
$ curl -o /dev/null -s -w %{time_total}\\n  https://iati-staging.ckan.io
1.225
$ curl -o /dev/null -s -w %{time_total}\\n  https://iati-staging.ckan.io/publisher
27.767
```

@wendyrogers is this the type of slow responses that you are experiencing?  Or are they slower in certain circumstances?

**Comment by dalepotter** [comment] 2016-09-07 08:58
Just an update that this one remains under investigation by @chrisviderum and team. The cross-browser testing website [Browserstack](https://www.browserstack.com) may be useful to test this issue further and understand how different browsers are affected.

I just made a quick account and saw some slow load times accessing `https://iati-staging.ckan.io/publisher` under Internet Explorer (v11) Firefox (v48.0) and Chrome (v52).  I timed Chrome at around 25 seconds, but did not use a stopwatch for the others.

**Comment by chrisviderum** [comment] 2016-09-07 16:47
@dalepotter @wendyrogers 

We will create a solution and give you an estimation on Friday. 

Tomorrow is a national holiday for most of our development staff, so I hope it is okay that you may receive it a bit after 9am London time.

**Comment by chrisviderum** [comment] 2016-09-09 17:37
Our estimation to fix this is 10 hours of work.

We would like to try a fix we have used for another big portal in the past to solve this performance issue.

But to be honest maybe it will be better to build in a pagination system with a search bar to search for specific publisher? This would take us 24 hours at all.

What do you think?

**Comment by dalepotter** [comment] 2016-09-13 14:16
Hi @chrisviderum, many thanks for this estimate. Would it be ok to ask for a bit of extra detail on the 10 hour time estimate - do you know what approach that the developers are suggesting?

Also, just thinking about the 24 hours to implement the pagination (guessing this is 3 days x 8 hours each?).  Without knowing the ins and outs of CKAN, this sounds like quite a long time for what appears to be a straightforward feature - is it that the way CKAN is designed makes it complex to implement, or perhaps our customisation has caused problems for this?

Many thanks,
Dale

**Comment by chrisviderum** [comment] 2016-09-14 03:25
Hey @dalepotter I can go back to me dev and ask for a more detailed break down.

In general the CKAN system is a bit complicated, as most things are working through overriding and adding other parts. This pagination system would be a new extension we need to build. In this 24 hours (3days x8hours is correct), we would develop the extension, write tests for it and test it on the new v2.5.2 portal.

Best,
Chris

**Comment by chrisviderum** [comment] 2016-09-19 12:53
@dalepotter here is the breakdwon of the 10 hours:

* Troubleshoot loading time issue (DB, Code, Web server): 7 hours
* Fix issue: 2.5 hours
* Regression test: 30 minutes
* Deploy to staging: 15 minutes

Note: Troubleshooting could be less time needed.

Some notes in addition (why my answer took so long): 

We did some investigations already:

Both staging and production use this API action in the code to get the list of organizations:

api/3/action/organization_list?all_fields=True

And, if this call is made from staging and production as well, similar results will be acquired. Meaning, It will take more than 10 seconds to get the results, which is a lot.

One thing to mention is, I think it is better if instead of showing the entire list of publishers, which is quite long (as of now there are almost 500 publishers), a pagination is a smarter solution, the same as on the page where datasets are shown. For instance, 20 items per page, and the page will load much faster.

My suspicion is that this API action, since does not return only the names of the organizations, but instead it returns other metadata for the organization, it takes that amount of time. The "all_fields" query parameter here indicates to return extra information for an organization. Here's how the result looks for one organization:

{
      "display_name": "Haitelmex Foundation ",
      "description": "",
      "image_display_url": "https://www.foundationhaitelmex.org ",
      "package_count": 0,
      "title": "Haitelmex Foundation ",
      "is_organization": true,
      "state": "active",
      "image_url": "https://www.foundationhaitelmex.org ",
      "type": "organization",
      "num_followers": 0,
      "id": "f78e4a4f-951e-43f8-843b-9d35f1dfa702",
      "name": "49374507"
}

The extra fields such as "package_count" and "num_followers" are not stored in the same table as the record for the organization, so it needs to do more computation to get them.

If the API action does not include the "all_fields" parameter, it loads the data in less than a second.

I have two solutions for this. We either try to index some of the columns that are required to gather the data, or instead of returning all organizations at once, we return only a portion of it, for example 20 items at once (paginatino).

The average median to load all organizations is 23.28s, while for 20 organizations is 1501ms, which is 15 times faster. 

We also have to take into account when the number of organizations increases over time, the loading times will be slower for getting all organizations without pagination.

**Comment by rory09** [comment] 2016-11-14 10:07
Hi All,

After a couple of days of intermittent gateway timeouts and public call-outs from users I've had a look into this issue, and I believe that this is actually a bug in v2.5.2 (possibly v2.5.x) of CKAN, and so should ideally be fixed within the CKAN codebase rather than on any given instance.

My suspicions were directed by the fact that this issue has only arisen after our upgrade to the newer version; the publisher page didn't grow substantially over night and it was fine before the upgrade. 

To test this, I've looked at other instances of CKAN at various versions, following @dalepotter's method above. Here are the results: 

| Site | CKAN Version | API Call | Time Taken (s) |
|----------|----------|----------|----------|
| https://iatiregistry.org/ | [2.5.2](https://iatiregistry.org/api/util/status) | curl -o /dev/null -s -w %{time_total}\\n  https://iatiregistry.org/api/3/action/organization_list?all_fields=true | 20.203 |
| http://demo.ckan.org/ | [2.5.2](http://demo.ckan.org/api/util/status) | curl -o /dev/null -s -w %{time_total}\\n  http://demo.ckan.org/api/3/action/organization_list?all_fields=true | 21.286 |
| https://data.gov.uk/ | [2.2b](https://data.gov.uk/api/util/status) | curl -o /dev/null -s -w %{time_total}\\n  https://data.gov.uk/api/3/action/organization_list?all_fields=true | 2.220 |
| https://datamillnorth.org/ | [2.4.2b](https://datamillnorth.org/api/util/status) | curl -o /dev/null -s -w %{time_total}\\n  https://datamillnorth.org/api/3/action/organization_list?all_fields=true | 0.696 |
| http://catalog.data.gov/ | [2.1a](http://catalog.data.gov/api/util/status) | curl -o /dev/null -s -w %{time_total}\\n  http://catalog.data.gov/api/3/action/organization_list?all_fields=true | 1.142 |

Given this, it seems clear to me that this is in fact a bug in the version of CKAN we've been upgraded to. Furthermore, given that we weren't especially keen to make this upgrade in the first place (and explicitly voiced worries about introducing any instability to our platform), I don't think it's reasonable for us to have to spend 10 hours of contracted support time to mitigate for it.

In this position I would recommend looking at a patch for v2.5.2 which could be applied across all instances with a system update, or something similar. I would be very surprised if we are the only users to be affected by this bug, and given that CKAN's own demo portal is similarly affected, I would strongly advise a instance-independent fix for all users, rather than a costly workaround for us.

I look forward to everyone's input on this, and would like to emphasise that we are already incurring reputational costs for this. Hence, I would politely request that this be treated as a matter of urgency.

Best,
Rory

P.S. for reference, I believe that the following lines are where the relevant differences between the versions can be found.

```yaml
Responsible Code
----------------

  Current & Buggy: 
    - "https://github.com/ckan/ckan/blob/ckan-2.5.2/ckan/logic/action/get.py#L498-L508"
  Old & Stable: 
    - "https://github.com/ckan/ckan/blob/ckan-2.2/ckan/logic/action/get.py#L373-L375"
```

**Comment by chrisviderum** [comment] 2016-11-16 14:20
Dear @rory09 , dear @dalepotter ,

Viderum's CKAN product manager brought this issue to the CKAN core developer group yesterday. I would like to summarize the feedback here:

The `all_fields` call is simply not designed to be called directly on a normal page like IATIs publisher list. It used to work in previous versions, but it will not work on modern CKANs. One of the group members worked on your portal during the creation process and he remembers many years ago that he already told you that this was not going to scale and that table pagination would be a better solution. 

This call is only be used, because you have extra fields to display on the publisher list (type, country, # of datasets). 

His suggestion is to solve this properly and create a view on the database that has exactly the fields they need, and then create a custom action (`organization_list_publisher_page` or sth. similar) that just returns this. 

Calling it here:

https://github.com/ViderumGlobal/ckanext-iati/blob/master/ckanext/iati/helpers.py#L243


@dalepotter we would start to work on this fix, as soon as you give your green light, as we see it as a critical issue. 

Thank you very much and best regards,

Chris

**Comment by dalepotter** [comment] 2016-11-16 14:32
Many thanks for this update @chrisviderum. Building a new database view sounds like a good way forward - yes please, let's go for this so that we can roll out a fix to this issue as soon as practical.

**Comment by chrisviderum** [comment] 2016-12-01 09:55
@dalepotter were you able to notice improvements of the publisher page speed? Like mentioned in an email last week we have created the new view and at least from our end it show improvements in speed and stability.

Thanks and best,

Chris

**Comment by chrisviderum** [comment] 2016-12-01 13:51
@wendyrogers can I close this ticket here, too?

**Comment by wendyrogers** [comment] 2016-12-01 14:02
Fine by me but  @dalepotter okay with you?

**Comment by dalepotter** [comment] 2016-12-02 15:05
Hi @chrisviderum many thanks for your time working on this and apologies for the delay in responding to you.  Yes I can confirm that the loading time for the [Registry list of publishers page](https://iatiregistry.org/publisher) is now typically around 4-6 seconds following testing amongst the team.

As such, I'll now close this ticket.

**Closed by dalepotter** 2016-12-02 15:05 UTC
Labels: planned
